[TLX] Throw error early if WS captures RankedTensorType (#284)
It will be problematic for ttgir conversion. Let's just throw error
early and tell the TLX users to move the code into ws regions, which is
also better for kernel perf.

Added a lit test. Also tested on blackwell with
`./third_party/tlx/run_all.sh`

Run a real tlx kernel with such violations:

```
test_kernel.py:150:9: error: WarpSpecializeOp should not capture RankedTensorType. Try moving tensor computation into specific async task.
    with tlx.async_tasks():
        ^
#blocked = #ttg.blocked< ...
...
```

It's more user friendly than previous error message:

```
error: 'ttg.warp_specialize' op partition region #0 argument #18 has type 'tensor<128xf32, #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [1], order = [0]}>>' but corresponding capture has type 'tensor<128xf32, #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>>'
    with tlx.async_tasks():
        ^
#blocked = #ttg.blocked ...
```