[TLX-3.5] Fix pytest python/triton_kernels/tests/test_matmul.py::test_op #306
Fix bug in _verify_loop_carried_variable

git difftool 2ac060b8b 330c88bb3 -- python/triton/compiler/code_generator.py

AssertionError: Loop-carried variable "i" has initial type constexpr_type[0] but is re-assigned to constexpr_type[1] in loop! Please make sure that the type stays consistent.

The above exception was the direct cause of the following exception:

Fix create_dot(): incompatible function arguments

    def make_ir(self, target: GPUTarget, options, codegen_fns, module_map, context):
        from .code_generator import ast_to_ttir
>       return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns,
                           module_map=module_map)
E       triton.compiler.errors.CompilationError: at 278:18:
E                       acc = acc.trans()
E                   else:
E                       rhs_k_pack: tl.constexpr = W_TRANSPOSE or not is_w_microscaled or W_K_DIVISOR != 2
E                       acc = tl.dot_scaled(x, x_scales, x_format, w, w_scales, w_format, acc=acc, fast_math=True, rhs_k_pack=rhs_k_pack)
E                   if SWIZZLE_MX_SCALE == "BLACKWELL_SCALE":
E                       WMxScalePtrs += (MX_SCALE_BLOCK_K // 4 * SPLIT_K) * stride_w_mx_k
E                   else:
E                       WMxScalePtrs += (PACKED_MX_BLOCK * SPLIT_K) * stride_w_mx_k
E                   if is_x_microscaled:
E                       XMxScalePtrs += (MX_SCALE_BLOCK_K * SPLIT_K) * stride_x_mx_k
E               else:
E                   acc = tl.dot(x, w, acc, max_num_imprecise_acc=MAX_NUM_IMPRECISE_ACC, allow_tf32=ALLOW_TF32)
E                         ^
E       create_dot(): incompatible function arguments. The following argument types are supported:
E           1. (self: triton._C.libtriton.ir.builder, arg0: triton._C.libtriton.ir.value, arg1: triton._C.libtriton.ir.value, arg2: triton._C.libtriton.ir.value, arg3: triton._C.libtriton.ir.INPUT_PRECISION, arg4: typing.SupportsInt) -> triton._C.libtriton.ir.value
E
E       Invoked with: <triton._C.libtriton.ir.builder object at 0x7f2176496090>, <triton._C.libtriton.ir.value object at 0x7f216be00570>, <triton._C.libtriton.ir.value object at 0x7f1f6402a3b0>, <triton._C.libtriton.ir.value object at 0x7f2176159130>, <INPUT_PRECISION.TF32: 0>, None

ensure type is checked if loop_val is buffered tensor

add additional check of has_type