[TLX] Fix incorrect dtype in propagate-layout.mlir (#285)
#278 introduced stronger verifications and surfaced the issues in test
`@gdpa_kernel_tma_ws_blackwell` where some ops have mix of f16 and bf16
like:

```
error: 'ttng.tmem_store' op source element type 'tensor<64x128xbf16, #ttg.blocked<{sizePerThread = [1, 64], threadsPerWarp = [16, 2], warpsPerCTA = [4, 1], order = [0, 1]}>>' must match destination element type 'f16'
            ttng.tmem_store %101, %100, %true : tensor<64x128xbf16, #blocked1> -> !ttg.memdesc<64x128xf16, #tmem, #ttng.tensor_memory, mutable>
            ^
```

This PR updates the test to just use bf16 all the time.