Fix bug in _verify_loop_carried_variable
git difftool 2ac060b8b 330c88bb3 -- python/triton/compiler/code_generator.py

AssertionError: Loop-carried variable "i" has initial type constexpr_type[0] but is re-assigned to constexpr_type[1] in loop! Please make sure that the type stays consistent.

The above exception was the direct cause of the following exception: